config/routes.rb
Rails.application.routes.draw do

  resources :counters

  resources :students

 #config/routes.rb

     # Serve websocket cable requests in-process

     mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counter.rb
class Counter < ApplicationRecord

  def increment!

      self.valeuer += 1

      ActionCable.server.broadcast('counters', self)

  end

end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController

   

  skip_before_action  :verify_authenticity_token, :only => [:update]

  

  before_action :set_counter, only: [:show, :edit, :update, :destroy]





  # GET /counters

  # GET /counters.json

  def index

    @counters = Counter.all

  end



  # GET /counters/1

  # GET /counters/1.json

  def show

  end



  # GET /counters/new

  def new

    @counter = Counter.new

  end



  # GET /counters/1/edit

  def edit

  end



  # POST /counters

  # POST /counters.json

  def create

    @counter = Counter.new(counter_params)



    respond_to do |format|

      if @counter.save

        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }

        format.json { render :show, status: :created, location: @counter }

      else

        format.html { render :new }

        format.json { render json: @counter.errors, status: :unprocessable_entity }

      end

    end

  end



  # PATCH/PUT /counters/1

  # PATCH/PUT /counters/1.json

  def update

    respond_to do |format|

      @counter.increment!

      if @counter.save()

        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }

        format.json { render :show, status: :ok, location: @counter }

      else

        format.html { render :edit }

        format.json { render json: @counter.errors, status: :unprocessable_entity }

      end

    end

  end



  # DELETE /counters/1

  # DELETE /counters/1.json

  def destroy

    @counter.destroy

    respond_to do |format|

      format.html { redirect_to counters_url, notice: 'Counter was successfully destroyed.' }

      format.json { head :no_content }

    end

  end



  private

    # Use callbacks to share common setup or constraints between actions.

    def set_counter

      @counter = Counter.find(params[:id])

    end



    # Never trust parameters from the scary internet, only allow the white list through.

    def counter_params

      params.require(:counter).permit(:name, :valeur)

    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :last_name, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/counters/_form.html.erb
<%= form_with(model: counter, local: true) do |form| %>
  <% if counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% counter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :valeuer %>
    <%= form.number_field :valeuer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing Counter</h1>

<%= render 'form', counter: @counter %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Counters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Valeuer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td><%= counter.name %></td>
        <td><%= counter.valeuer %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/new.html.erb
<h1>New Counter</h1>

<%= render 'form', counter: @counter %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @counter.name %>
</p>

<p>
  <strong>Valeuer:</strong>
  <%= @counter.valeuer %>
</p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YANZeyu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.birthday %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @student.birthday %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>